### ISSUE TITLE
No release?

### ISSUE THREAD

**Issue by olivierlambert** [42wim/matterbridge-plus#1]
Hi!

Can't find a binary nor the install with `go get`. The link to the binary is broken. I'm no `go` expert, do I miss something?

**Comment by olivierlambert** [comment]
Hmm my bad, seems to be fixed after calling `go get` multiple times. But the broken link in the readme stills apply ;)

**Comment by 42wim** [comment]
I'm waiting on feedback of people like you to let me know if there are any issues before I release ;-)

**Comment by olivierlambert** [comment]
Okay, let's play :)
