### ISSUE TITLE
Can not connect

### ISSUE THREAD

**Issue by olivierlambert** [42wim/matterbridge-plus#2]
Installed `matterbridge-plus` on the same box that running Mattermost. Mattermost is behind a NGINX proxy redirecting everything in HTTPS (301)

In settings, if I use:

```
server="mattermost.mydomain.tld"
```

Got: `can not connect`

Now, if I try:

```
server="https://mattermost.mydomain.tld"
```

Got: `LOGIN: /users/login: , Post https://http://mattermost.mydomain.tld/api/v1/users/login: dial tcp <my IP address>:0: connection refused, reconnecting in 1.852727759s`

See the double `http(s)` in the URL

**Comment by 42wim** [comment]
Matterbridge-plus only supports https connections to mattermost.
Is your server running on 443 ? If so and if it's running on the same box, try 127.0.0.1 or the ip mattermost is bound to.

**Comment by olivierlambert** [comment]
Mattermost itself is only running locally, HTTPS is done with Nginx reverse proxy.

**Comment by 42wim** [comment]
If you do a curl https://mattermost.mydomain.tld on the same server where you try matterbridge-plus, does it work ?
Did you try with the IP address instead of mattermost.mydomain.tld ?

**Comment by aatchison** [comment]
I seem to be having the same issue. Mattermost 2.0 and matterbridge-plus are on the same box with SSL terminated via Nginx. 127.0.0.1 doesn't work either. I can connect to IRC ok, and there are no error logs for the Mattermost instance that I can find. If I log out of Mattermsot as the matterbridge user, I can see that it's not logged in.
I get the error, 'retrying login' from matterbridge-plus, and that's about all I can see.
If I curl the domain locally with no http, I get a 301, as I should.  With https:// I get a 'Temperary Redirect'

**Comment by 42wim** [comment]
Can you let me know if the current version still gives you problems?
