### ISSUE TITLE
Binary release for 0.3?

### ISSUE THREAD

**Issue by mlutfy** [42wim/matterbridge-plus#24]
Hi,

Version 0.2 of matterbridge-plus had a binary release for Linux. Is it still available for 0.3? I didn't see in the release notes, only source archives.

Thanks!
Mathieu

PS: we use this to sync #civicrm on Freenode with our instance of Mattermost. Much appreciated!

**Comment by 42wim** [comment]
Hi, I've updated the release with a linux binary, enjoy!
