### ISSUE TITLE
filtering by nick?

### ISSUE THREAD

**Issue by JoeMurray** [42wim/matterbridge-plus#25]
CiviCRM is just starting to use mattermost, and will need to slowly transition folks from our long-standing irc channel that many of them love. We've been having our github activity auto-posted to irc. We have a separate channel for that in mattermost. We'd like to reduce the noise in our bridge from mattermost to irc by filtering the github posts (it's many times the posting frequency of humans). This seems like a fairly common use case. Harrison Healey suggested I post it here as a feature request.

**Comment by 42wim** [comment]
Ok, good idea. I've just implemented this. 

You'll have to rebuild matterbridge-plus from master.

Then add  `IgnoreNicks = "nick1 nick2"` to either `[mattermost]` section if you want to ignore sending from specific mattermost users to irc. Or you can add it to the `[irc]` section if you want to ignore sending from irc to mattermost.

Als an example in the README.md

**Comment by JoeMurray** [comment]
Working great in production. Thanks!!
