### ISSUE TITLE
Disable certificate verification option

### ISSUE THREAD

**Issue by glattercj** [42wim/matterbridge-plus#26]
This might be related to #2, but I'm not sure. I have matterbridge-plus installed on the same system as mattermost, with nginx in between for SSL (with self-signed cert). Here's what I'm seeing (X's are sanitized input):

``` bash
./matterbridge-plus-linux64 -debug
INFO[2016-05-26T04:02:51Z] enabling debug
running version 0.3.1
DEBU[2016-05-26T04:02:51Z] trying login myteam botuser X.X.X.X  module=matterclient
DEBU[2016-05-26T04:02:51Z] Post https://X.X.X.X/api/v3/users/login: x509: certificate signed by unknown authority  module=matterclient
FATA[2016-05-26T04:02:51Z] can not connectmodel.client.connecting.app_error  module=mattermost
```

In my config, I have `UseTLS=false`, `SkipTLSVerify=true`. If I try to curl my server with the `-k` option, it works fine. Is there a way to disable certificate verification on matterbridge-plus? I thought that's what the "SkipTLSVerify" option was for.

Any ideas?

**Comment by 42wim** [comment]
Fixed in latest master, you'll need to add  `SkipTLSVerify=true`  to the `[mattermost]` section.
Remove `UseTLS=false` this only works for the IRC section where TLS/SSL is disabled by default.

For mattermost  TLS/SSL is enabled by default, to disable it (http-only) you'll need to set `NoTLS=true` (but that's not your usecase).

**Comment by glattercj** [comment]
This seems to have fixed my issue. Thanks!

**Comment by ghost** [comment]
I am getting a similar error for running matterbridge plus. Kindly assist me to resolve.

This is my conf file : 
[IRC]
server="irc.freenode.net"
port=6667
UseTLS=false
SkipTLSVerify=true
nick="matterbot"
UseSlackCircumfix=false
#NickServNick="nickserv"
#NickServPassword="secret"
RemoteNickFormat="<{NICK}> "
IgnoreNicks="ircspammer1 ircspammer2"

[mattermost]
server="http://localhost:8065/"
#certificate check by default
SkipTLSVerify=true
#https by default
NoTLS=true
team="enterp"
#login/pass of your bot
login="aaa555"
password="passwordtest"
showjoinpart=true
#token="k5isyh7n4fy5m*********"
PrefixMessagesWithNick=false
NickFormatter=plain
NicksPerRow=4
RemoteNickFormat="[irc] <{NICK}>"
IgnoreNicks="mmbot spammer2"

[general]
GiphyAPIKey=dc6zaTOxFJmzC

#channel config
[channel "town-square"]
irc="#bottesting"
mattermost="testing"

[channel "off-topic"]
irc="#random"
mattermost="random"

Also this is the command i run and the error : 

vaaa1tt@vaaa1tt:~/work/bin$ ./matterbridge-plus 
running version 0.4
INFO[2016-06-29T13:00:10Z] Trying login ewurama555 (team: enterprisenurs) on http://localhost:8063/  module=mattermost
FATA[2016-06-29T13:00:11Z] Can not connectmodel.client.connecting.app_error  module=mattermost
