### ISSUE TITLE
UNKNOWN EVENT log messages, no messages from bot

### ISSUE THREAD

**Issue by winged** [42wim/matterbridge-plus#27]
I have a setup that properly connects to a private IRC server and a 3.0.0 MM instance.

Unfortunately, it just logs "UNKNOWN EVENT" when typing anything on both sides. Here's what happens (log entries redacted for privacy):
### Writing to IRC channel

```
level=info msg="UNKNOWN EVENT: &irc.Event{Code:\"PRIVMSG\", Raw:\":mynick!dv@somehostname PRIVMSG #test :yo\", Nick:\"mynick\", Host:\"somehostname\", Source:\"mynick!dv@somehostname\", User:\"dv\", Arguments:[]string{\"#test\", \"yo\"}, Connection:(*irc.Connection)(0xc8203c0360)}" module=irc
```
### Writing to MM Channel

```
level=info msg="UNKNOWN EVENT: &irc.Event{Code:\"412\", Raw:\":the.irc.server 412 bot-username :No text to send\", Nick:\"\", Host:\"\", Source:\"the.irc.server\", User:\"\", Arguments:[]string{\"bot-username\", \"No text to send\"}, Connection:(*irc.Connection)(0xc8203c0360)}" module=irc
```

Not sure if its a misconfiguration or a bug.

**Comment by 42wim** [comment]
The "bot" is a dedicated user, it only relays messages from other users. Not from itself, don't login via the webinterface as the bot, but use your own account.

**Comment by winged** [comment]
Yes, that's what I've done :) Note that it doesn't relay anything in either direction at the moment.

For reference, here's my config (redacted of course):

```
[IRC]
server="irc.example.com"
port=6697
UseTLS=true
SkipTLSVerify=true
nick="mmbot"
UseSlackCircumfix=false
IgnoreNicks=""
RemoteNickFormat="<{NICK}> "

[mattermost]
server="mm.example.com"
login="irrc"
password="thepassword"
team="myteam"
showjoinpart=true
SkipTLSVerify=false
PrefixMessagesWithNick=true
NickFormatter=plain
NicksPerRow=4

[general]
GiphyAPIKey=dc6zaTOxFJmzC

[channel "Town Square"]
irc="#test"
mattermost="Town Square"
```

**Comment by 42wim** [comment]
Try changing `mattermost="Town Square"` to `mattermost=town-square`
Channel must be same as in Web url

**Comment by winged** [comment]
Thanks a lot, this solved it! Added a PR to explicitly mention this.
