### ISSUE TITLE
Login fails when using gitlab-mattermost that requires SSO via gitlab

### ISSUE THREAD

**Issue by daysofwineandroses** [42wim/matterbridge-plus#3]
Hey Wim,

In our setup we have a self-hosted gitlab, which has an integrated mattermost setup.

See: 
- http://doc.gitlab.com/omnibus/gitlab-mattermost/
- https://gitlab.com/gitlab-org/gitlab-mattermost

When logging in to mattermost via the browser, you get the option to use gitlab as authentication source (which we enforce as only option, because we use AD in the background for our users).

![mm_gitlab_login](https://cloud.githubusercontent.com/assets/10164075/12623965/e1eaca8a-c52c-11e5-8c2a-b2de2103b02c.png)

After clicking the button, if you are not already logged in to gitlab, an extra window opens and lets you enter your credentials. After authenticating, you get logged in into mattermost.

`matterbridge-plus` fails here because it doesn't know about this authentication mechanism:

```
$ ./matterbridge-plus -conf="matterbridge-plus.conf" 
2016/01/27 19:27:03 retrying login <teamname> <email> mattermost.localdomain.local
2016/01/27 19:27:03 can not connectPlease sign in using gitlab
```

Would it be possible to add support for this SSO mechanism? I'm not at home in this kind of web programming.

It would be nice to make the bridge between our externally available irc server and our internal mattermost machine.

It works very well with the normal matterbridge setup using webhooks, but having it working like this seemed a bit cleaner and more straightforward than configuring the webhooks on a user.

I'd be happy to help in providing further info and testing if needed.

Thanks in advance!

**Comment by 42wim** [comment]
Yes, this would be nice but it's not possible at the moment. See also https://github.com/42wim/matterircd/issues/29 
I'll close this ticket now, when it gets into matterircd, matterbridge-plus will also get it.

**Comment by andynd** [comment]
this is still broken. any news?

**Comment by 42wim** [comment]
@andynd It's nothing that I can fix (I think) see https://github.com/mattermost/platform/pull/1938 and 42wim/matterircd#29

Note that matterbridge-plus is deprecated, you should move to https://github.com/42wim/matterbridge
