### ISSUE TITLE
Unknown Event irc->mattermost messages

### ISSUE THREAD

**Issue by JJWTimmer** [42wim/matterbridge-plus#30]
Using master (I think.. `go get github.com/42wim/matterbridge-plus`):
When I submit a message in mattermost, it goes to the relevant irc channel, but the otherway around I see this in the bridge log and the message does not arrive in mattermost:

```
INFO[2016-06-18T13:36:10Z] UNKNOWN EVENT: &irc.Event{Code:"PRIVMSG", Raw:":JJWTimmer!~Jasper@2001:982:17de:1:54a1:d573:77c8:3e53 PRIVMSG #botTesting :hello?", Nick:"JJWTimmer", Host:"2001:982:17de:1:54a1:d573:77c8:3e53", Source:"JJWTimmer!~Jasper@2001:982:17de:1:54a1:d573:77c8:3e53", User:"~Jasper", Arguments:[]string{"#botTesting", "hello?"}, Connection:(*irc.Connection)(0xc8201598c0)}  module=irc
```

It's not a private message as far as I can tell, but just a regular IRC message.

**Comment by 42wim** [comment]
could you run with -debug and paste the debug log ? be sure to blank out personal info/passwords

**Comment by JJWTimmer** [comment]
Here you have the log: [log.txt](https://github.com/42wim/matterbridge-plus/files/321933/log.txt)
I couldn't find personal info in there except my name. Last message is the one I sent as a test from IRC and I expect it in mattermost.

**Comment by JJWTimmer** [comment]
Appartently I'm kind of blind. I'm seeing my messages now. Sorry for the fuzz.
