### ISSUE TITLE
Can not connectmodel.client.connecting.app_error module=mattermost

### ISSUE THREAD

**Issue by ghost** [42wim/matterbridge-plus#31]
I am getting an error for running matterbridge plus. (I have my matterbridge.conf file in the same directory as the matterbridge-plus executable i.e /home/work/bin) Kindly assist me to resolve.

**This is my conf file :** 

[IRC]
server="irc.freenode.net"
port=6667
UseTLS=false
SkipTLSVerify=true
nick="matterbot"
UseSlackCircumfix=false
# NickServNick="nickserv"
# NickServPassword="secret"

RemoteNickFormat="<{NICK}> "
IgnoreNicks="ircspammer1 ircspammer2"

[mattermost]
server="http://localhost:8065/"
# certificate check by default

SkipTLSVerify=true
# https by default

NoTLS=true
team="enterp"
# login/pass of your bot

login="aaa555"
password="passwordtest"
showjoinpart=true
# token="k5isyh7n4fy5m*********"

PrefixMessagesWithNick=false
NickFormatter=plain
NicksPerRow=4
RemoteNickFormat="[irc] <{NICK}>"
IgnoreNicks="mmbot spammer2"

[general]
GiphyAPIKey=dc6zaTOxFJmzC
# channel config

[channel "town-square"]
irc="#bottesting"
mattermost="testing"

[channel "off-topic"]
irc="#random"
mattermost="random"

**Also this is the command i run and the error :**

vaaa1tt@vaaa1tt:~/work/bin$ ./matterbridge-plus 
running version 0.4
INFO[2016-06-29T13:00:10Z] Trying login aaa555 (team: enterp) on http://localhost:8065/ module=mattermost
FATA[2016-06-29T13:00:11Z] Can not connectmodel.client.connecting.app_error module=mattermost

**Comment by 42wim** [comment]
Please run with -debug option

**Comment by ghost** [comment]
@42wim  I have just run with -debug option

vaaa1tt@vaaa1tt:~/work/bin$ ./matterbridge-plus -debug
INFO[2016-06-29T16:56:28Z] enabling debug  
running version 0.4
INFO[2016-06-29T16:56:28Z] Trying login aaa555 (team: enterp) on http://localhost:8065/  module=mattermost
DEBU[2016-06-29T16:56:28Z] trying login enterp aaa555 http://localhost:8065/  module=matterclient
DEBU[2016-06-29T16:56:28Z] Post https://http://localhost:8065//api/v3/users/login: dial tcp: lookup http on 127.0.1.1:53: no such host  module=matterclient
FATA[2016-06-29T16:56:28Z] Can not connectmodel.client.connecting.app_error  module=mattermost

**Comment by 42wim** [comment]
Remove http:// from server="http://localhost:8065/"
Just put 127.0.0.1:8065

**Comment by ghost** [comment]
@42wim   Great!! thanks it worked. But i also had to change all accept TLS settings to false.

So now i want to know how i can use xchat to get messages to and from my mattermost. im making it run on 8063 now and my XChat irc client says connection closed by peer.

snapshot here 
![xchat and matterbridge plus](https://cloud.githubusercontent.com/assets/7202129/16463123/e1ad1134-3e23-11e6-8ccb-72641c3716b8.jpg)

**Comment by 42wim** [comment]
Xchat can not connect to mattermost.  You'll need matterircd to bridge between Xchat and mattermost

**Comment by ghost** [comment]
@42wim  Thanks very much. Now i have installed matterircd and it connect fine on xchat , but it listens on 127.0.0.1:6667 and has no channels.

How can i make it listen to my mattermost server  ? which is on 10.10.9.1:8065 ??

**Comment by 42wim** [comment]
Please read the matterircd documentation
you can do /msg mattermost login

**Comment by ghost** [comment]
Thanks @42wim ,  I have read the matterircd documentation. But when i run the command i get no feedback and I am not able to access the channels. Please help me figure out what i may be doing wrong:

i type this in xchat after i connect it to matterircd on 127.0.0.1:6667

/msg LOGIN 127.0.0.1 enterp eoko@gmail.com Dr****

Im not sure what exactly im typing wrong. 

this is my xchat login success interface

![image](https://cloud.githubusercontent.com/assets/7202129/16486772/59f929c4-3eb6-11e6-8710-0f36346224a0.png)

Also i went to the network list and created another server with credentials of my mattermost server, but that gives me an error. please see below :+1: 
- 
- Disconnected (Remote host closed socket).
  Cycling to next server in mattermost2...
- Disconnected ().
- Looking up 127.0.0.1
- Connecting to 127.0.0.1 (127.0.0.1) port 8063...
- Connected. Now logging in...
- HTTP/1.1 400 Bad Request
- Content-Type: text/plain
- Connection: close
-

**Comment by 42wim** [comment]
Documentation says /msg mattermost login <server> <team> <username>

You did not specify 'mattermost'

**Comment by ghost** [comment]
@42wim  Thanks , now i connected with the XChat and i type this command to login:

**/msg mattermost login 10.8.22.9:8065 enterprise-nurs moljjkkkk@yahoo.com Drjkjkjkj**

This is the error returned inside xchat windows
**<mattermost> model.client.connecting.app_error
<mattermost> model.client.connecting.app_error
<mattermost> model.client.connecting.app_error**

Also below is the error returned inside the matterircd console on the terminal

**INFO[2016-06-30T12:49:32Z] login as nurs (team: enterprise-nurs) on 10.8.22.9:8065  module=matterircd
ERRO[2016-06-30T12:49:32Z] login failed                                  module=matterircd
INFO[2016-06-30T12:50:09Z] login as nurs (team: enterprise-nurs) on 10.8.22.9:8065  module=matterircd
ERRO[2016-06-30T12:50:09Z] login failed                                  module=matterircd**

**Comment by 42wim** [comment]
As found in the documentation 
`-mminsecure` use http connection to mattermost

**Comment by ghost** [comment]
@42wim    Im so grateful. It works perfectly!!! thanks.

**Comment by 42wim** [comment]
Happy to know it works!
